language: c

services:
- docker

before_install:
- docker pull cortesja/stm32-cmake:latest

script:
- docker run --rm -v $(pwd):/home/stm32/ws cortesja/stm32-cmake:latest bash -c "sh build.sh"